import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-dark-background dark:text-dark-foreground`}
      >
        {/* Add the Toaster Component in Root 
        layout (Render toaster at root layout*/}
        <Toaster position="top-right" expand={false} richColors />
        {/* As a props we can pass position also like top-left/top-center/top-right/bottom-left/bottom-center/bottom-right  and default-color, and expand-{true/false} */}
        {children}

        {/* we can pass multiple toaster */}
        <Toaster
          id="global"
          position="top-center"
          expand
          visibleToasts={5} // 5 toasts will be visible
          offset={16} // all sides will have 16px offset
          mobileOffset={{ bottom: "16px" }}
        />
        <Toaster id="canvas" position="bottom-right" offset="10vh" />
      </body>
    </html>
  );
}
